heat_template_version: 2015-04-30

parameters:
  bmc_flavor:
    type: string

  bmc_image:
    type: string

  baremetal_flavor:
    type: string

  baremetal_image:
    type: string

  key_name:
    type: string

  bmc_prefix:
    type: string

  baremetal_prefix:
    type: string

  private_net:
    type: string

  private_sg:
    type: string

  networks:
    type: comma_delimited_list

  suffix:
    type: string

  os_user:
    type: string

  os_password:
    type: string
    hidden: true

  os_tenant:
    type: string

  os_auth_url:
    type: string

resources:

  bmc_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - ''
        - - {get_param: bmc_prefix}
          - {get_param: suffix}
      network: {get_param: private_net}

  baremetal_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: baremetal_flavor}
      image: {get_param: baremetal_image}
      config_drive: false
      key_name: {get_param: key_name}
      networks:
        repeat:
          for_each:
            <%network%>: {get_param: networks}
          template:
            network: <%network%>

      name:
        list_join:
        - ''
        - - {get_param: baremetal_prefix}
          - {get_param: suffix}

outputs:
  bmc_nic:
    value: {port: {get_resource: bmc_port}}
