heat_template_version: 2014-10-16

description: Template for deploying OpenStack BMC nodes.  Can be wrapped in a ResourceGroup for scaling.

# Ensure force_config_drive is _not_ set in nova.conf

parameters:
  bmc_flavor:
    type: string
    default: m1.small

  bmc_image:
    type: string
    default: openstack-bmc

  baremetal_flavor:
    type: string
    default: baremetal
    description: Recommended to be at least 1 vcpu, 4 GB RAM, 50 GB disk

  baremetal_image:
    type: string
    default: empty

  key_name:
    type: string
    default: default

  node_count:
    type: number
    default: 1

  private_net:
    type: string
    default: private

  provision_net:
    type: string
    default: provision

  bmc_prefix:
    type: string
    default: bmc

  baremetal_prefix:
    type: string
    default: baremetal

  os_user:
    type: string
    default: admin

  os_password:
    type: string
    default: password
    hidden: true

  os_tenant:
    type: string
    default: admin

  os_auth_url:
    type: string

resources:
  provision_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: provision_sg
      description: Allows all traffic
      rules:
      - protocol: icmp
      - protocol: tcp
      - protocol: udp

  private_sg:
    type: OS::Neutron::SecurityGroup
    properties:
      name: private_sg
      description: Ping, SSH and IPMI
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
      - protocol: udp
        port_range_min: 623
        port_range_max: 623

  openstack_bmc_servers:
    type: OS::Heat::ResourceGroup
    properties:
      count: {get_param: node_count}
      resource_def:
        type: OS::QuintupleO::BMC
        properties:
            bmc_flavor: {get_param: bmc_flavor}
            bmc_image: {get_param: bmc_image}
            baremetal_flavor: {get_param: baremetal_flavor}
            baremetal_image: {get_param: baremetal_image}
            key_name: {get_param: key_name}
            private_net: {get_param: private_net}
            private_sg: {get_resource: private_sg}
            provision_net: {get_param: provision_net}
            provision_sg: {get_resource: provision_sg}
            suffix: _%index%
            bmc_prefix: {get_param: bmc_prefix}
            baremetal_prefix: {get_param: baremetal_prefix}
            os_user: {get_param: os_user}
            os_password: {get_param: os_password}
            os_tenant: {get_param: os_tenant}
            os_auth_url: {get_param: os_auth_url}
