heat_template_version: 2014-10-16

parameters:
  bmc_flavor:
    type: string

  bmc_image:
    type: string

  baremetal_flavor:
    type: string

  baremetal_image:
    type: string

  key_name:
    type: string

  bmc_prefix:
    type: string

  baremetal_prefix:
    type: string

  public_net:
    type: string

  public_sg:
    type: string

  private_net:
    type: string

  private_sg:
    type: string

  provision_net:
    type: string

  provision_sg:
    type: string

  suffix:
    type: string

  os_user:
    type: string

  os_password:
    type: string
    hidden: true

  os_tenant:
    type: string

  os_auth_url:
    type: string

resources:

  bmc_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - ''
        - - {get_param: bmc_prefix}
          - {get_param: suffix}
      network: {get_param: private_net}
      security_groups:
      - {get_param: private_sg}

  baremetal_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - ''
        - - {get_param: baremetal_prefix}
          - {get_param: suffix}
      network: {get_param: provision_net}
      security_groups:
      - {get_param: provision_sg}

  baremetal_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: baremetal_flavor}
      image: {get_param: baremetal_image}
      config_drive: false
      key_name: {get_param: key_name}
      # security_groups:
      # TODO(bnemec): Reattach these when it doesn't wreak havoc on TripleO to have multiple nics.
      #- {get_param: public_sg}
      networks:
      - port: {get_resource: baremetal_port}
      #- network: {get_param: public_net}
      name:
        list_join:
        - ''
        - - {get_param: baremetal_prefix}
          - {get_param: suffix}

outputs:
  bmc_nic:
    value: {port: {get_resource: bmc_port}}
