heat_template_version: 2014-10-16

parameters:

  baremetal_flavor:
    type: string

  baremetal_image:
    type: string

  key_name:
    type: string

  bmc_prefix:
    type: string

  baremetal_prefix:
    type: string

  private_net:
    type: string

  provision_net:
    type: string

  suffix:
    type: string

resources:

  bmc_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - ''
        - - {get_param: bmc_prefix}
          - {get_param: suffix}
      network: {get_param: private_net}

  baremetal_port:
    type: OS::Neutron::Port
    properties:
      name:
        list_join:
        - ''
        - - {get_param: baremetal_prefix}
          - {get_param: suffix}
      network: {get_param: provision_net}

  baremetal_server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: baremetal_flavor}
      image: {get_param: baremetal_image}
      config_drive: false
      key_name: {get_param: key_name}
      networks:
      - port: {get_resource: baremetal_port}
      name:
        list_join:
        - ''
        - - {get_param: baremetal_prefix}
          - {get_param: suffix}

outputs:
  bmc_nic:
    value: {port: {get_resource: bmc_port}}
